name:                optimum
version:             0.1.0.0
author:              Alex McKenna
maintainer:          alexmckenna@outlook.com
category:            Numeric
synopsis:            Declarative Numeric Optimization
description:         See README.md
github:              alex-mckenna/optimum
license:             MIT
copyright:           2019 Alex McKenna

ghc-options:
- -fhide-source-paths
- -Wall
- -Wcompat
- -Werror
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-signatures
- -Wsimplifiable-class-constraints

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

  exposed-modules:
  - Numeric.Optimization
  - Numeric.Optimization.Dummy
  - Numeric.Optimization.Problem
  - Numeric.Optimization.Solver
  - Numeric.Optimization.Trace
  - Numeric.Optimization.TwoPhase

  dependencies:
  - finite-typelits
  - hmatrix
  - hmatrix-vector-sized
  - vector
  - vector-sized

